### ISSUE TITLE
No grabber working

### ISSUE THREAD

**Issue by taz4hvn** [jeka-js/alexandra#27]
Built 1.5.0 today on Arch, currently it seems no grabber is working, IMDB says "movie not found" and OMDB says "authentification required", only the first grabber whose name is cyrillic gives something.

**Comment by jeka-js** [comment]
Hi,

thank you for your report. I already fixed the issues and you can try it from the master branch (fixed IMDB parser, added OMDb API key field to settings dialog (seems like API key is required since some time, it wasn't before), also added proxy server configuration if needed).

Best regards,
Eugene

**Comment by taz4hvn** [comment]
Thank you for the update. I tried the IMDB grabber and it works now, can't tell for OMDb since I don't have an API key. If the project is still active you may want to consider adding TMDb support since it's maybe the best db of it's kind.

**Comment by jeka-js** [comment]
Hmm, TMDb is looking good, not sure why I did not use it before.
I think I will add the support for its API, just can't tell when, because have not much free time unfortunately.
